config/routes.rb
Rails.application.routes.draw do

  resources :contents
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'

  post '/compra/:slug', to: 'transactions#create', as: :compra
  get '/pickup/:guid', to: 'transactions#pickup', as: :pickup

  get 'dashboard' => 'pages#dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  extend FriendlyId
  friendly_id :titolo, use: :slugged
  belongs_to :user
  has_many :sales

  has_attached_file :cover
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

  has_attached_file :allegato
  validates_attachment_content_type :allegato, :content_type => [ /^image\/(png|gif|jpeg)/,'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation', 'application/pdf', 'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','audio/mpeg', 'audio/mp3' ],
  message: "Formato non supportato"

  validates :titolo, :descrizione, :price, presence: true
  validates :price, numericality: { greater_than: 0.49 }

  validates :cover, attachment_presence: true
end

app/models/sale.rb
class Sale < ApplicationRecord
  before_create :generate_guide
  belongs_to :content
  include AASM

  aasm column: 'state' do
    state :sleeping, initial: true
    state :running, :completed
    state :errored

    event :running, after: :charge_card do
      transitions from: :sleeping, to: :running
    end

    event :complete do
      transitions from: :running, to: :completed
    end

    event :fail do
      transitions from: :running, to: :errored
    end


  end

  def charge_card
    begin
      save!
      charge = Stripe::Charge.create(
        amount: self.amount,
        currency: "eur",
        card: self.stripe_token,
        description: "vendita di un contenuto"
      )
      self.update(stripe_id: charge.id)
      self.complete!
    rescue Stripe::StripeError => e
      self.update_attributes(error: e.message)
      self.fail!
    end
  end

  private

  def generate_guide
    self.guid = SecureRandom.uuid()
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contents

  validates :name, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?

  before_action :authenticate_user!

  private
      # Its important that the location is NOT stored if:
      # - The request method is not GET (non idempotent)
      # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
      #    infinite redirect loop.
      # - The request is an Ajax request as this can lead to very unexpected behaviour.
      def storable_location?
        request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
      end

      def store_user_location!
        # :user is the scope we are authenticating
        store_location_for(:user, request.fullpath)
      end


  protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
 end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @contents = Content.all.paginate(page: params[:page], per_page: 4).order('created_at DESC')
  end

  def show
  end

  def new
    @content = current_user.contents.build
  end

  def edit
  end

  def create
    @content = current_user.contents.build(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Contentuto creato con successo.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: 'Contentuto aggiornato con successo.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Il contentuto è stato eliminato.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def content_params
      params.require(:content).permit(:titolo, :descrizione, :price, :cover, :allegato)
    end

    def check_user
      if current_user != @content.user
        redirect_to root_url, alert: 'Non hai accesso a questa pagina'
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only:[:dashboard]
  def home
  end

  def about
  end

  def dashboard
    @content = current_user.contents
    @sales = Sale.where(email_venditore: current_user.email)
    @purchased = Sale.where(email_acquirente: current_user.email)
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def create
    content = Content.find_by!(slug: params[:slug])
    sale = content.sales.create(
      amount: (content.price * 100).floor,
      email_acquirente: current_user.email,
      email_venditore: content.user.email,
      stripe_token: params[:stripeToken]
    )
    sale.running!
    if sale.completed?
      redirect_to pickup_url(guid: sale.guid)
    else
      redirect_to content_path(content), notice: @error
    end
  end

  def pickup
    @sale = Sale.find_by!(guid: params[:guid])
    @content = @sale.content
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contents/_form.html.erb
<%= form_for @content, html: {multipart: true} do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(content.errors.count, "errori") %> non permettono al form di essere inviato</h4>

      <ul>
      <% @content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :carica_il_contenuto %>
    <br>
    <%= form.file_field :allegato %>
  </div>
  <br>
  <div class="field">
    <%= form.label :titolo %>
    <%= form.text_field :titolo %>
  </div>

  <div class="field">
    <%= form.label :descrizione %>
    <%= form.text_area :descrizione, class: 'materialize-textarea' %>
  </div>

  <div class="field">
    <%= form.label :prezzo_min_50_cent %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :carica_immagine_da_utilizzare_come_cover %>
    <br>
    <%= form.file_field :cover %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit 'Salva Contenuto', class: 'btn' %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<h1 class="center">Modifica Contenuto <%= @content.titolo %> </h1>

<%= render 'form', content: @content %>

<%= link_to 'Mostra contenuto', @content %> |
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/index.html.erb
<h1>Contents</h1>

<div class="row">
  <% @contents.each do |content| %>
    <div class="col s12 m6 l4">
      <div class="card">
         <div class="card-image waves-effect waves-block waves-light">
           <%= image_tag content.cover.url, class: 'activator' %>
         </div>
         <div class="card-content">
           <span class="card-title activator grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">more_vert</i></span>
           <div>
             <span>Venduto da <%= content.user.name %></span>
             <span class="right"> <%= number_to_currency(content.price) %></span>
           </div>
           <br>
           <div class="center">
             <%= link_to 'Scopri di più', content, class: 'btn' %>
           </div>
         </div>
         <div class="card-reveal">
           <span class="card-title grey-text text-darken-4"><%= content.titolo %><i class="material-icons right">close</i></span>
           <p><%= content.descrizione %>.</p>
         </div>
       </div>
    </div>
  <% end %>
</div>

<br>

<div class="center">
  <%= will_paginate @contents %>
</div>

app/views/contents/new.html.erb
<h1 class="center">Vendi un contenuto digitale</h1>

<%= render 'form', content: @content %>

<%= link_to 'Torna ai contenuti', contents_path %>

app/views/contents/show.html.erb
<div class="content-show">
  <div class="row">
    <div class="col l6">
      <%= image_tag @content.cover.url, class: 'responsive-img' %>
    </div>
    <div class="col l6">
      <p>
        <strong>Titolo:</strong>
        <%= @content.titolo %>
      </p>
        <strong>Venduto da:</strong>
        <%= @content.user.name %>
      <p>
      </p>
      <p>
        <strong>Descrizione:</strong>
        <%= @content.descrizione %>
      </p>
      <p>
        <strong>Prezzo:</strong>
        <%= number_to_currency (@content.price) %>
      </p>
      <% if current_user %>

      <%= form_tag compra_path(slug: @content.slug) do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= (@content.price * 100).floor %>"
          data-name="LuigiMarket"
          data-description="<%= @content.titolo %>"
          data-email="<%= current_user.email %>"
          data-locale="auto"
          data-currency="eur">
        </script>
      <% end %>
    </div>
  </div>
</div>


<% else %>
  <p>Fai Login <%= link_to "Login", new_user_session_path %> oppure <%= link_to "Registrati",
    new_user_registration_path %> per poter acquistare questo contenuto</p>
<% end %>

<% if @content.user == current_user %>
  <%= link_to 'Modifica', edit_content_path(@content) %> |
<% end %>
<%= link_to 'Torna ai contenuti', contents_path %>

app/views/layouts/_footer.html.erb
<footer class="page-footer blue-grey darken-2 center">
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col s4">
            © 2019 LuigiMarket
        </div>
        <div class="col s4">
        <a href="www.facebook.com" target="_blank"><i class="fa-social fa fa-facebook fa-2x white-text"></i></a>
        <a href="www.twitter.com" target="_blank"><i class="fa-social fa fa-twitter fa-2x white-text"></i></a>
        </div>
        <div class="col s4">
          <%= link_to "About", about_path, class: "grey-text text-lighten-3 right" %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar-fixed">
  <nav class="blue-grey darken-2">
    <div class="container nav-wrapper">
      <%= link_to "LuigiMarket", root_path, class:"brand-logo fa fa-floppy-o fa-2x white-text" %>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to 'Vendi Contenuto', new_content_path %></li>
        <% if user_signed_in? %>

        <ul id='dropdown1' class='dropdown-content'>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Impostazioni", edit_user_registration_path %></li>
          <li class="divider" tabindex="-1"></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        </ul>
        <li><a class='dropdown-trigger btn' href='#!' data-target='dropdown1'><%= current_user.name %></a></li>

        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Registrazione", new_user_registration_path %></li>
        <% end %>
      </ul>
      <ul class="sidenav" id="mobile-demo">
        <li><%= link_to 'Vendi Contenuto', new_content_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Impostazioni", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Registrazione", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuigiMarket</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
<body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |type, message| %>
      <script>
        M.toast({html: '<%= message %>'})
      </script>
      <% end %>
    </div>

    <%= render "pages/slider" if action_name == 'home' %>

    <main class="container">
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
</body>
  <script>
    $(document).ready(function(){
      $('.sidenav').sidenav();
    });
  </script>

  <script>
    $(document).ready(function(){
      $('ul.tabs').tabs();
    });
  </script>

  <script>
    $(document).ready(function(){
      $('.dropdown-trigger').dropdown();
    });
  </script>

  <script>
    $(document).ready(function(){
        $('.parallax').parallax();
      });
  </script>



</html>

app/views/pages/_slider.html.erb
<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <div class="row center">
        <h1>LuigiMarket</h1>
        <h5>Vendi e acquista contenuti digitali</h5>
      </div>
      <div class="row center">
        <%= link_to "Vai a contenuti", contents_path, class: "btn red btn-large" %>
      </div>
      <br><br>

    </div>
  </div>
  <div class="parallax"> <%= image_tag("background1.jpg") %></div>
</div>

app/views/pages/about.html.erb
<h1>Chi Siamo</h1>
<p>Sono un ragazzo che sta imparando Rails</p>

app/views/pages/dashboard.html.erb
<h1 class="center">Dashboard</h1>

<div class="row">
   <div class="col s12">
     <ul class="tabs">
       <li class="tab col s3"><a href="#storico">Storico</a></li>
       <li class="tab col s3"><a href="#vendita">In Vendita</a></li>
     </ul>
   </div>

   <div id="storico" class="col s12">
     <h4>Vendite</h4>
     <table>
       <thead>
         <tr>
           <th>Nome</th>
           <th>Prezzo</th>
           <th>Data</th>
           <th>Acquirente</th>
         </tr>
        </thead>
        <tbody>
           <% @sales.each do |sale| %>
           <tr>
             <th><%= sale.content.titolo %></th>
             <th><%= number_to_currency(sale.amount / 100) %></th>
             <th><%= time_ago_in_words(sale.created_at) %> fa</th>
             <th><%= sale.email_acquirente %>
             </th>
           </tr>
           <% end %>
         </tbody>
     </table>

      <br>
      <br>
     <h4>Acquisti</h4>

     <table>
       <thead>
         <tr>
           <th>Nome</th>
           <th>Prezzo</th>
           <th>Data di creazione</th>
           <th>email venditore</th>
         </tr>
        </thead>
        <tbody>
           <% @purchased.each do |purchase| %>
           <tr>
             <th><%= link_to purchase.content.titolo, pickup_path(purchase.guid) %></th>
             <th><%= number_to_currency(purchase.amount / 100) %></th>
             <th><%= time_ago_in_words(purchase.created_at) %> fa</th>
             <th><%= purchase.email_venditore %></th>
           </tr>
           <% end %>
         </tbody>
     </table>

   </div>


   <div id="vendita" class="col s12">
     <table>
       <thead>
         <tr>
           <th>Nome</th>
           <th>Prezzo</th>
           <th>Data creazione</th>
           <th>Azioni</th>
         </tr>
        </thead>
        <tbody>
           <% @content.each do |content| %>
           <tr>
             <th><%= link_to content.titolo, content_path(content) %></th>
             <th><%= content.price %></th>
             <th><%= content.created_at %></th>
             <th><%= link_to "Modifica", edit_content_path(content) %> |
               <%= link_to "Elimina", content, method: :delete, data: {confirm: 'Sei sicuro di volere cancellare questo contenuto?'} %>
             </th>
           </tr>
           <% end %>
         </tbody>
     </table>
   </div>
 </div>

app/views/pages/home.html.erb
<div class="center">
  <div class="row">
    <h2 class="home-subtitle">Il negozio online di contenuti digitali</h2>
    <div class="col s12 m4">
        <i class="material-icons medium blue-grey-text-darken-3">library_books</i>
        <h5 >Scopri contenuti unici</h5>

        <p>Scegli tra i formati disponibili il documento che stai cercando</p>
    </div>

    <div class="col s12 m4">
      <i class="material-icons medium blue-grey-text-darken-3">motorcycle</i>
        <h5 class="center">Acquista velocemente</h5>

        <p>Scegli il prodotto che ti interessa e in pochi secondi potrai iniziare ad utilizzarlo</p>
    </div>

    <div class="col s12 m4">
      <i class="material-icons medium blue-grey-text-darken-3">library_add</i>
        <h5 class="center">Vendi i tuoi contenuti</h5>

        <p>Hai documenti che vorresti vendire? Aggiungili alla libreria e inizia a guadagnare</p>
    </div>
  </div>

</div>

app/views/transactions/pickup.html.erb
<h1>Grazie per aver acquistato <%= @content.titolo  %></h1>

<p><%= link_to "Scarica qui", @content.cover.url %> il tuo contenuto</p>